name: 'GhostAPI Security Scan'
description: 'AI-powered API security audit for your CI/CD pipeline. Block insecure deployments automatically.'
author: 'GhostAPI'
branding:
  icon: 'shield'
  color: 'green'

inputs:
  api-key:
    description: 'Your GhostAPI API key (from CI/CD Pro subscription)'
    required: true
  openapi-path:
    description: 'Path to your OpenAPI spec file (JSON or YAML)'
    required: true
  min-grade:
    description: 'Minimum grade to pass (A, B, C, D, F). Default: C'
    required: false
    default: 'C'
  fail-on-error:
    description: 'Whether to fail the workflow if scan fails'
    required: false
    default: 'true'

outputs:
  passed:
    description: 'Whether the security check passed'
  grade:
    description: 'Security grade (A-F)'
  score:
    description: 'Security score (0-100)'
  vulnerabilities:
    description: 'Number of vulnerabilities found'
  report-url:
    description: 'URL to full report'

runs:
  using: 'node20'
  main: 'dist/index.js'
